"""Add time stamps

Revision ID: 68cf50f7563b
Revises: 91a24c8041df
Create Date: 2025-10-30 09:31:05.173954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cf50f7563b'
down_revision: Union[str, Sequence[str], None] = '91a24c8041df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('members', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('members', 'total_amount_received',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.alter_column('members', 'total_amount_received',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('members', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('members', 'updated_at')
    op.drop_column('members', 'created_at')
    # ### end Alembic commands ###
