"""create members table

Revision ID: 85c0324b68c1
Revises: 
Create Date: 2025-10-13 16:32:19.553467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c0324b68c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('members', sa.Column('address', sa.String(), nullable=False))
    op.add_column('members', sa.Column('city', sa.String(), nullable=False))
    op.add_column('members', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('members', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('members', sa.Column('join_date', sa.Date(), nullable=False))
    op.add_column('members', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('total_amount_received', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'total_amount_received')
    op.drop_column('members', 'active')
    op.drop_column('members', 'join_date')
    op.drop_column('members', 'phone')
    op.drop_column('members', 'postal_code')
    op.drop_column('members', 'city')
    op.drop_column('members', 'address')
    op.drop_column('members', 'birth_date')
    # ### end Alembic commands ###
